# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
name: Reel 2 Reel Podcast
title: Reel 2 Reel Podcast | A podcast about your favourite celebrities and box office hits
email: reel2reelpodcast@gmail.com
description: Listen to Mike & Mark go reel 2 reel on your favourite actors every week, and bring you all the latest movie news, gossip, and reviews. Now in podcast and article form!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://reel2reelpod.com" # the base hostname & protocol for your site
twitter_username: reel2reelpod
social_username: reel2reelpodcast

rose_about: Mike and Mark bring you <strong>Rose 2 Rose</strong>, a podcast about all things The Bachelor (including The Bachelorette Canada!) They love Jasmine and have lots of thoughts on some of the great and terrible men vying for her affections.

mike_twitter: https://twitter.com/ohmikegraham
mark_twitter: https://twitter.com/MarkySports

# Build settings
markdown: kramdown

permalink: :year/:month/:day/:title/

gems:
  - jekyll-sitemap

port: 4002